
model: "assets/models/yolo11s-seg_optim.dxnn"

workers:
  preprocess: 1
  wait: 1
  postprocess: 2
  draw: 1

channels:
  - name: "ch1"
    type: "video"
    source: "assets/videos/cctv-city-road.mov"
    enabled: true
    max_fps: 25

  - name: "ch2"
    type: "video"
    source: "assets/videos/dron-citry-road.mov"
    enabled: true
    max_fps: 25

  - name: "ch3"
    type: "video"
    source: "assets/videos/carrierbag.mp4"
    enabled: true
    max_fps: 25

  - name: "ch4"
    type: "video"
    source: "assets/videos/dance-group.mov"
    enabled: true
    max_fps: 25

# rtsp example
#  - name: "ch4"
#    type: "rtsp"
#    source: "rtsp://username:password@ip_address:port/stream"
#    enabled: true
#    max_fps: 25

# camera example
#  - name: "ch4"
#    type: "camera"
#    source: 0
#    enabled: true
#    max_fps: 25